services:
  db:
    image: mysql:8.0
    container_name: expertlink-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cpt202_consultancy
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expertlink-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/cpt202_consultancy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: expertlink-pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 12345
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expertlink-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend

volumes:
  db_data:
