package edu.xjtlu.cpt202.backend.modules.ai.model.vo;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

/**
 * @author QiranXiao
 * @since 2026/4/15
 */
@Data
@Builder
@Schema(description = "AI chat stream chunk")
public class ChatStreamVO {

    @Schema(description = "Chunk content generated by AI")
    private String content;

    @Schema(description = "Whether current stream is completed")
    private Boolean done;
}
