spring:
  application:
    name: backend
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    fail-on-missing-locations: true

server:
  port: 8081

# Logging
logging:
  level:
    edu.xjtlu.cpt202.backend: DEBUG
    org.springframework.web: DEBUG
    org.flywaydb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# MyBatis Plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deletedAt
      logic-delete-value: "now()"
      logic-not-delete-value: "null"
