name: Deploy to Aliyun Server

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 15m
          script: |
            cd /home/workspace/CPT202
            
            git fetch origin
            git reset --hard origin/deploy
            git pull origin deploy
            
            docker-compose up -d --build --force-recreate
            
            docker image prune -af